spring:
  application:
    name: springboot-feign-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 2021
management:
  endpoints:
    web:
      exposure:
        include: "*"