server:
  port: 2021
spring:
  application:
    name: springboot-feign-provider
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckInterval: 15s
management:
  endpoints:
    web:
      exposure:
        include: "*"