version: '3.7'
services:
  nacos:
    image: nacos/nacos-server:2.0.0
    container_name: nacos-standalone
    environment:
      - MODE=standalone
    ports:
      - 8848:8848
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.20.0
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:7.1.0
    ports:
      - 3000:3000
    depends_on:
      - nacos
    restart: on-failure