version: '3.7'
services:
  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch-master
    environment:
      - node.name=master
      - cluster.name=springboot-elasticsearch
      - discovery.seed_hosts=elasticsearch-slave
      - cluster.initial_master_nodes=master,slave
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xss512k -XX:NewRatio=1 -Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastaticsearch/master/data:/usr/share/elasticsearch/data
      - ./elastaticsearch/master/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - net-es
  elasticsearch-slave:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch-slave
    environment:
      - node.name=slave
      - cluster.name=springboot-elasticsearch
      - discovery.seed_hosts=elasticsearch-master
      - cluster.initial_master_nodes=master,slave
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xss512k -XX:NewRatio=1 -Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastaticsearch/slave/data:/usr/share/elasticsearch/data
      - ./elastaticsearch/slave/logs:/usr/share/elasticsearch/logs
    networks:
      - net-es
    depends_on:
      - elasticsearch-master
    external_links:
      - elasticsearch-master
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kibana
    environment:
      - SERVER_NAME=kibana-server
      - ELASTICSEARCH_HOSTS=http://elasticsearch-master:9200
    ports:
      - 5601:5601
    networks:
      - net-es
    depends_on:
      - elasticsearch-master
    external_links:
      - elasticsearch-master
networks:
  net-es:
    driver: bridge