version: '3.7'
services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: mysql-dockerfile
    environment:
          - "MYSQL_ROOT_PASSWORD=martin-local"
          - "MYSQL_ROOT_HOST=%"
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    ports:
      - 3306:3306
    networks:
      - net-springboot
  zoo1:
    image: zookeeper:3.4
    container_name: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    networks:
      - net-springboot
    external_links:
      - zoo2
  zoo2:
    image: zookeeper:3.4
    container_name: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    networks:
      - net-springboot
    external_links:
      - zoo1
  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch-master
    restart: always
    environment:
      - node.name=master
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=springboot-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastaticsearch/master-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - net-springboot
  elasticsearch-slave:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch-slave
    restart: always
    environment:
      - node.name=slave
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=springboot-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch-master"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastaticsearch/slave-data:/usr/share/elasticsearch/data
    networks:
      - net-springboot
    depends_on:
      - elasticsearch-master
    external_links:
      - elasticsearch-master
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    restart: always
    environment:
      - SERVER_NAME=kibana-server
      - ELASTICSEARCH_URL=http://elasticsearch-master:9200
    ports:
      - 5601:5601
    networks:
      - net-springboot
    depends_on:
      - elasticsearch-master
    external_links:
      - elasticsearch-master
  redis:
    image: redis:5.0
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    restart: always
    volumes:
          - ./redis/:/etc/redis/
    ports:
      - 6379:6379
    networks:
      - net-springboot
  memcached:
    image: memcached:1.5
    container_name: memcached
    restart: always
    ports:
      - 11211:11211
    networks:
      - net-springboot
  namesrv:
    image: rocketmqinc/rocketmq:4.2.0
    container_name: rmqnamesrv
    command: sh mqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./rocketmq/namesrv/:/home/rocketmq/
      - ./rocketmq/namesrv/:/home/rocketmq/
    networks:
      - net-springboot
  broker:
    image: rocketmqinc/rocketmq:4.2.0
    container_name: rmqbroker
    restart: always
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./rocketmq/broker/:/home/rocketmq/
      - ./rocketmq/broker/:/home/rocketmq/
      - ./rocketmq/broker/conf/broker.conf:/opt/rocketmq-4.2.0/conf/broker.conf
    networks:
      - net-springboot
    depends_on:
      - namesrv
networks:
  net-springboot:
    driver: bridge