version: '3.7'
services:
  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch-master
    restart: always
    environment:
      - node.name=master
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=springboot-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastaticsearch/master-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - net-es
  elasticsearch-slave:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch-slave
    restart: always
    environment:
      - node.name=slave
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=springboot-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch-master"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastaticsearch/slave-data:/usr/share/elasticsearch/data
    networks:
      - net-es
    depends_on:
      - elasticsearch-master
    external_links:
      - elasticsearch-master
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    restart: always
    environment:
      - SERVER_NAME=kibana-server
      - ELASTICSEARCH_URL=http://elasticsearch-master:9200
    ports:
      - 5601:5601
    networks:
      - net-es
    depends_on:
      - elasticsearch-master
    external_links:
      - elasticsearch-master
networks:
  net-es:
    driver: bridge