server:
  port: 2019
spring:
  shardingsphere:
    datasource:
      ds-0:
        url: jdbc:mysql://127.0.0.1:3306/spring_project_1
        username: root
        password: martin-local
      ds-1:
        url: jdbc:mysql://127.0.0.1:3306/spring_project_2
        username: root
        password: martin-local
  data:
    elasticsearch:
      cluster-name: springboot-elasticsearch
      cluster-nodes: 127.0.0.1:9300
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  application:
    name: springboot-web-local
  registry:
    address: zookeeper://127.0.0.1:2181
  reference:
    firstDubbo:
      version: 1.0-local
rocketmq:
  name-server: 127.0.0.1:9876
memcached:
  address: 127.0.0.1:11211
zookeeper:
  address: 127.0.0.1:2181
nacos:
  config:
    server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"