server:
  port: 2019
spring:
  datasource:
    url: jdbc:shardingsphere:classpath:sharding-db.yml
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
dubbo:
  application:
    name: springboot-web-local
  registry:
    address: zookeeper://127.0.0.1:2181
  reference:
    firstDubbo:
      version: 1.0-local
rocketmq:
  name-server: 127.0.0.1:9876
memcached:
  address: 127.0.0.1:11211
zookeeper:
  address: 127.0.0.1:2181
nacos:
  config:
    server-addr: 127.0.0.1:8848
logging:
  level:
    com.doodl6.springboot.dao.mapper: DEBUG
