spring:
  application:
    name: springboot-dubbo-provider
  profiles:
    active: local
dubbo:
  scan:
    base-packages: com.doodl6.springboot.dubbo.provider.service
  protocol:
    name: dubbo
    port: 20880