spring:
  application:
    name: springboot-dubbo-provider
  profiles:
    active: local
dubbo:
  application:
    qos-port: 20990
  metrics:
    protocol: prometheus
  protocol:
    rest:
      port: 8080
    dubbo:
      port: 20880