server:
  port: 2020
spring:
  shardingsphere:
    datasource:
      ds-0:
        url: jdbc:mysql://127.0.0.1:3306/spring_project_1
        username: root
        password: martin-local
      ds-1:
        url: jdbc:mysql://127.0.0.1:3306/spring_project_2
        username: root
        password: martin-local
dubbo:
  application:
    name: springboot-dubbo-service-local
  registry:
    address: zookeeper://127.0.0.1:2181
  service:
    firstDubbo:
      version: 1.0-local